create table public.answers (
  id bigint generated by default as identity,
  text varchar(255) not null,
  step_id bigint,
  primary key (id)
);
create table public.exercises_tags (
  exercise_id bigint not null,
  tag_id bigint not null,
  primary key (exercise_id, tag_id)
);
create table public.permissions (
  id bigint generated by default as identity,
  code varchar(255) not null,
  primary key (id)
);
create table public.roles (
  id bigint generated by default as identity,
  code varchar(255) not null,
  description varchar(255) not null,
  title varchar(255) not null,
  primary key (id)
);
create table public.roles_permissions (
  role_id bigint not null,
  permission_id bigint not null,
  primary key (role_id, permission_id)
);
create table public.steps (
  id bigint generated by default as identity,
  order_num integer not null,
  text varchar(255) not null,
  exercise_id bigint not null,
  primary key (id)
);
create table public.tags (
  id bigint generated by default as identity,
  title varchar(255) not null,
  primary key (id)
);
create table public.user_answers (
  created_at timestamp not null,
  step_id bigint not null,
  user_id bigint not null,
  success boolean not null,
  text varchar(255) not null,
  primary key (created_at, step_id, user_id)
);
create table public.users (
  id bigint generated by default as identity,
  email varchar(255) not null,
  name varchar(255) not null,
  role_id bigint not null,
  primary key (id)
);
create table public.words (
  id bigint generated by default as identity,
  source varchar(255) not null,
  translation varchar(255) not null,
  step_id bigint,
  primary key (id)
);
create table exercises (
  id bigint generated by default as identity,
  title varchar(255) not null,
  creator_id bigint not null,
  from_id bigint not null,
  to_id bigint not null,
  primary key (id)
);
create table languages (
  id bigint generated by default as identity,
  code varchar(255) not null,
  title varchar(255) not null,
  primary key (id)
);

alter table public.permissions add constraint UK_7lcb6glmvwlro3p2w2cewxtvd unique (code);
alter table public.roles add constraint roles_unique_code unique (code);
alter table public.roles add constraint roles_unique_title unique (title);
alter table public.steps add constraint roles_unique_exercise_id_order unique (exercise_id, order_num);
alter table public.tags add constraint tags_unique_title unique (title);
alter table public.users add constraint users_unique_email unique (email);
alter table exercises add constraint exercises_unique_title unique (title);
alter table languages add constraint languages_unique_title unique (title);
alter table languages add constraint languages_unique_code unique (code);

alter table public.answers add constraint FK7reypmf72wokapr0h18umbgx5 foreign key (step_id) references public.steps;
alter table public.exercises_tags add constraint FKbjm93sb95ni3whd8i9s1mpeih foreign key (tag_id) references public.tags;
alter table public.exercises_tags add constraint FK93pni3upemi5t7gi5krbijr6a foreign key (exercise_id) references exercises;
alter table public.roles_permissions add constraint FKbx9r9uw77p58gsq4mus0mec0o foreign key (permission_id) references public.permissions;
alter table public.roles_permissions add constraint FKqi9odri6c1o81vjox54eedwyh foreign key (role_id) references public.roles;
alter table public.steps add constraint FKigrjwtt0ulapdemqk6qqg6um4 foreign key (exercise_id) references exercises;
alter table public.user_answers add constraint FKa45sfws99rr6qtgq5yftuxw8u foreign key (step_id) references public.steps;
alter table public.users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references public.roles;
alter table public.words add constraint FKmhtwe2qqkw7nt9txwnrclh9yc foreign key (step_id) references public.steps;
alter table exercises add constraint FKs6xree4vwj2ytcdsxy5v3xwk2 foreign key (creator_id) references public.users;
alter table exercises add constraint FKtm6el21j2n6ua3xsbbsatsch foreign key (from_id) references languages;
alter table exercises add constraint FKrdgc8n6ki71nt46cc1uh0p6nr foreign key (to_id) references languages;
