spring:
  datasource:
    # PostgreSQL credentials will be provided as env variables by heroku
    platform: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
    # connection pool
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 2
  jpa:
    #    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate #none
      show-sql: false
  flyway:
    locations: classpath:db/migration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(iwx4W0T/0Dj10G1pPNW8OwyfRek6oekyJH0CG/cQRMbPCxnJjBh3ztpomF6VN963pHgC3LNoOQw7gxM8PJ4Agxx7odj1gAUV2LYZ4f1FekKPsKQACMtk6Mvs27G93/Kw2/I1y3FMERaFtmf/4yLtPQ==)
            client-secret: ENC(Jub8pgjK0BTwxcy1yTrZKf1EvOm3znqgbkqbEIXWM/SqKGMTntd58rzqnvtyS3E+5VHgTydwZH8Meb0IHGSU0w==)
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
          github:
            client-id: ENC(sh9TWCg9ajtKHnfYZTv/5Mt61SVjp1Otw6bVv6zL89XvEngL04VTuywxTqVavHXtY+mNJ8MdHvumvyNywJzNMg==)
            client-secret: ENC(7urOpi5frnM7gcAm14+x4TifeiTPGhexA4Unh8fgpWaqoV9JqG/ec8GpFvQkwQbO424HicV2zfGY/Qbcst7bXgicAT2uNSUzSYjAgUQzRdI=)
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"

  mvc:
    throw-exception-if-no-handler-found: true

app:
  auth:
    tokenSecret: ENC(S7PG/KWB3NPf/XP/bmnsuts7sft5rUH1lTvxJ8tMxu4Gpp5msSBjdsWyuZdqESZQ93Gmgvw3S5AVVIAqBoL/+U82wAjltY5IdAA1vPKSbYk=)
    tokenExpirationMsec: 864000000

jasypt:
  encryptor:
    bean: translatesStringEncryptor
