spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    # H2
    url: jdbc:h2:mem:testdb #file:~/testdb # mem:testdb
    username: sa
    password: password
    platform: h2
    driver-class-name: org.h2.Driver
    # connection pool
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 3
  #    initialization-mode: never
  jpa:
    #    properties:
    #      javax:
    #        persistence:
    #          schema-generation:
    #            create-source: metadata
    #            scripts:
    #              action: create
    #              create-target: create.sql
    hibernate:
      ddl-auto: create #none
      show-sql: false
      dialect: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(ddn14RhBYeB45J4HODKlou6ifTZpBP2U169ETC2B9fWFqAiCBC6wNZpLEIBIbftyqBxEwC8ckLgXtxFIPE38zZ75Q10L44hMKUagcpKMY5HOjI8PckQCmRUoV71RrMTvISP3e+ZZT6Xif1kBv15gKQ==)
            client-secret: ENC(oPHvjo6+vDq3anLHeheFeCqY1U3UKJH/SeSq5cM/yCsAZAmB8DHFfiIJTN5Zr1I7FxsDlr5Ff76MEyUAUs75vQ==)
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  #         github:
  #           client-id: ENC(ZCJD2N0Dv4M0g0rwxoL/1ALEHvJcs8nldrnfRoQt4mqOnEyR9SCuCJAcQcFNc6vvJhhj1IidAYVRZs4K3q/s+A==)
  #           client-secret: ENC(KNkDOygBNyteH2s4WDoQaNJ88FDht4G595CsV25PEogkQcbUDnUZaDZcF2RoJjP5dQBw18/691GyB07EW6TxcOtHiPQKVVypkxNad+CwUDI=)

  flyway:
    enabled: false

  mvc:
    throw-exception-if-no-handler-found: true

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000

jasypt:
  encryptor:
    bean: translatesStringEncryptor